# Generated by Django 4.2.16 on 2026-06-09 06:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tickets', '0001_initial'),
        ('sla', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sla',
            name='ticket',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tickets.ticket'),
        ),
    ]
