# Generated by Django 4.2.16 on 2026-06-28 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_rank'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_default_password',
            field=models.BooleanField(default=True, help_text='Indicates if user is still using the default password (support123)'),
        ),
        migrations.AddField(
            model_name='user',
            name='last_password_change',
            field=models.DateTimeField(blank=True, help_text='Timestamp of the last password change', null=True),
        ),
    ]
