# Generated by Django 4.2.16 on 2026-07-16 21:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_team_lead'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='team',
        ),
        migrations.AddField(
            model_name='user',
            name='teams',
            field=models.ManyToManyField(blank=True, related_name='members', to='users.team'),
        ),
        migrations.AlterField(
            model_name='team',
            name='lead',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leading_teams', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_default_password',
            field=models.BooleanField(default=True, help_text='Indicates if user is still using the default password'),
        ),
        migrations.DeleteModel(
            name='UserTeam',
        ),
    ]
