# Generated by Django 4.2.16 on 2026-06-11 02:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0002_channel_created_at_channel_status_channel_updated_at'),
        ('tickets', '0003_ticket_category_issuetemplate_ticket_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='channel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='channels.channel'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='priority',
            field=models.CharField(default='MEDIUM', max_length=20),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(default='OPEN', max_length=20),
        ),
    ]
