# Generated by Django 4.2.16 on 2026-06-11 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0002_channel_created_at_channel_status_channel_updated_at'),
        ('tickets', '0004_alter_ticket_channel_alter_ticket_priority_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='issuetemplate',
            options={'ordering': ['name'], 'verbose_name': 'Issue Template', 'verbose_name_plural': 'Issue Templates'},
        ),
        migrations.AddField(
            model_name='issuetemplate',
            name='channels',
            field=models.ManyToManyField(blank=True, related_name='issue_templates', to='channels.channel'),
        ),
        migrations.AddField(
            model_name='issuetemplate',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterModelTable(
            name='issuetemplate',
            table='issue_templates',
        ),
    ]
