# Generated by Django 4.2.29 on 2026-06-04 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_alter_district_options_alter_region_options_and_more'),
        ('tickets', '0004_ticket_district_ticket_region_ticket_street_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='customer_contact',
            new_name='customer_email',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='district',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='region',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='street',
        ),
        migrations.AddField(
            model_name='ticket',
            name='customer_phone',
            field=models.CharField(default='Not Provided', max_length=100),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='ward',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='locations.ward'),
        ),
    ]
