# Generated by Django 4.2.16 on 2026-06-11 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0005_alter_issuetemplate_options_issuetemplate_channels_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other'), ('N', 'Prefer not to say')], help_text='Gender of the customer', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='nida_number',
            field=models.CharField(blank=True, help_text='National ID number (NIDA) – optional, must be unique if provided', max_length=20, null=True, unique=True),
        ),
    ]
