# Generated by Django 4.2.16 on 2026-06-11 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0006_customer_gender_customer_nida_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], help_text='Gender of the customer', max_length=1, null=True),
        ),
    ]
