# Generated by Django 4.2.16 on 2026-06-11 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0007_alter_customer_gender'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='customer',
            constraint=models.CheckConstraint(check=models.Q(('gender__in', ['M', 'F']), ('gender__isnull', True), _connector='OR'), name='valid_gender_constraint'),
        ),
    ]
