# Generated by Django 4.2.16 on 2026-06-11 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0008_customer_valid_gender_constraint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='nida_number',
            field=models.CharField(blank=True, help_text='National ID number (NIDA)', max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='total_open',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='customer',
            name='total_resolved',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='customer',
            name='total_tickets',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
