# Generated by Django 4.2.16 on 2026-06-05 09:45

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tickets', '0008_ticket_ticket_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATED', 'Ticket Created'), ('UPDATED', 'Ticket Updated'), ('COMMENTED', 'Comment Added'), ('STATUS_CHANGED', 'Status Changed'), ('PRIORITY_CHANGED', 'Priority Changed'), ('ASSIGNED', 'Assigned'), ('UNASSIGNED', 'Unassigned'), ('ATTACHMENT', 'Attachment Added'), ('RESOLVED', 'Resolved'), ('CLOSED', 'Closed'), ('REOPENED', 'Reopened')], db_index=True, help_text='Type of action performed', max_length=50)),
                ('old_status', models.CharField(blank=True, max_length=50, null=True)),
                ('new_status', models.CharField(blank=True, max_length=50, null=True)),
                ('old_priority', models.CharField(blank=True, max_length=20, null=True)),
                ('new_priority', models.CharField(blank=True, max_length=20, null=True)),
                ('old_assignee', models.CharField(blank=True, max_length=255, null=True)),
                ('new_assignee', models.CharField(blank=True, max_length=255, null=True)),
                ('comment', models.TextField(blank=True, null=True, validators=[django.core.validators.MinLengthValidator(1, 'Comment cannot be empty')])),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional data like attachment names, old values, etc.')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ticket_histories', to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='histories', to='tickets.ticket')),
            ],
            options={
                'verbose_name': 'Ticket History',
                'verbose_name_plural': 'Ticket Histories',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['ticket', '-created_at'], name='tickets_tic_ticket__e69b72_idx'), models.Index(fields=['action', 'created_at'], name='tickets_tic_action_6cd58c_idx')],
            },
        ),
    ]
