# Generated by Django 4.2.16 on 2026-06-05 10:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0009_tickethistory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tickethistory',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='tickethistory',
            name='action',
            field=models.CharField(choices=[('CREATED', 'Ticket Created'), ('UPDATED', 'Ticket Updated'), ('COMMENTED', 'Comment Added'), ('STATUS_CHANGED', 'Status Changed'), ('PRIORITY_CHANGED', 'Priority Changed'), ('ASSIGNED', 'Assigned'), ('UNASSIGNED', 'Unassigned'), ('ATTACHMENT', 'Attachment Added'), ('RESOLVED', 'Resolved'), ('CLOSED', 'Closed'), ('REOPENED', 'Reopened')], db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='tickethistory',
            name='comment',
            field=models.TextField(blank=True, null=True, validators=[django.core.validators.MinLengthValidator(1)]),
        ),
        migrations.AlterField(
            model_name='tickethistory',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
