# Generated by Django 4.2.16 on 2026-06-11 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0009_alter_customer_gender_alter_customer_nida_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
