# Generated by Django 4.2.16 on 2026-06-05 11:11

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tickets', '0010_alter_tickethistory_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='customer_email',
            field=models.CharField(blank=True, default='Not Provided', max_length=100),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='customer_name',
            field=models.CharField(blank=True, default='Unknown', max_length=255),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='customer_phone',
            field=models.CharField(blank=True, default='Not Provided', max_length=100),
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(db_index=True, max_length=255)),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True, validators=[django.core.validators.EmailValidator(message='Enter a valid email address')])),
                ('phone', models.CharField(db_index=True, max_length=20, validators=[django.core.validators.RegexValidator(message='Phone number must be in international format', regex='^\\+?1?\\d{9,15}$')])),
                ('alternate_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('company_name', models.CharField(blank=True, max_length=255, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('country', models.CharField(default='Tanzania', max_length=100)),
                ('postal_code', models.CharField(blank=True, max_length=20, null=True)),
                ('preferred_contact_method', models.CharField(choices=[('EMAIL', 'Email'), ('PHONE', 'Phone'), ('SMS', 'SMS'), ('WHATSAPP', 'WhatsApp')], default='EMAIL', max_length=20)),
                ('preferred_language', models.CharField(default='en', max_length=10)),
                ('notes', models.TextField(blank=True, help_text='Internal notes about the customer', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_ticket_created', models.DateTimeField(blank=True, null=True)),
                ('total_tickets', models.IntegerField(default=0)),
                ('total_resolved', models.IntegerField(default=0)),
                ('total_open', models.IntegerField(default=0)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customers_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Customer',
                'verbose_name_plural': 'Customers',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='ticket',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='tickets.customer'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['email', 'phone'], name='tickets_cus_email_df6739_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['full_name'], name='tickets_cus_full_na_b1d223_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['-total_tickets'], name='tickets_cus_total_t_616c05_idx'),
        ),
    ]
