# Generated by Django 4.2.16 on 2026-06-11 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0010_ticket_deleted_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickethistory',
            name='new_team',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tickethistory',
            name='old_team',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
