# Generated by Django 4.2.16 on 2026-07-17 00:26

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tickets', '0011_tickethistory_new_team_tickethistory_old_team'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='customer',
            name='valid_gender_constraint',
        ),
        migrations.AlterField(
            model_name='customer',
            name='address',
            field=models.TextField(blank=True, help_text='Physical address', null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='alternate_phone',
            field=models.CharField(blank=True, help_text='Alternate phone number', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='city',
            field=models.CharField(blank=True, help_text='City', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='company_name',
            field=models.CharField(blank=True, help_text='Company name if applicable', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='country',
            field=models.CharField(default='Tanzania', help_text='Country', max_length=100),
        ),
        migrations.AlterField(
            model_name='customer',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Date and time when customer was created'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this customer', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customers_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(blank=True, db_index=True, help_text="Customer's email address (optional)", max_length=254, null=True, validators=[django.core.validators.EmailValidator(message='Enter a valid email address')]),
        ),
        migrations.AlterField(
            model_name='customer',
            name='full_name',
            field=models.CharField(db_index=True, help_text="Customer's full name", max_length=255),
        ),
        migrations.AlterField(
            model_name='customer',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other'), ('N', 'Not Specified')], help_text="Customer's gender", max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='last_ticket_created',
            field=models.DateTimeField(blank=True, help_text='Date and time of last ticket created by this customer', null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='notes',
            field=models.TextField(blank=True, help_text='Additional notes about the customer', null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(db_index=True, help_text="Customer's phone number (required)", max_length=20, validators=[django.core.validators.RegexValidator(message='Phone number must be in international format', regex='^\\+?1?\\d{9,15}$')]),
        ),
        migrations.AlterField(
            model_name='customer',
            name='postal_code',
            field=models.CharField(blank=True, help_text='Postal code', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='preferred_contact_method',
            field=models.CharField(choices=[('EMAIL', 'Email'), ('PHONE', 'Phone'), ('SMS', 'SMS'), ('WHATSAPP', 'WhatsApp')], default='EMAIL', help_text='Preferred contact method', max_length=20),
        ),
        migrations.AlterField(
            model_name='customer',
            name='preferred_language',
            field=models.CharField(default='en', help_text='Preferred language', max_length=10),
        ),
        migrations.AlterField(
            model_name='customer',
            name='state',
            field=models.CharField(blank=True, help_text='State or region', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='total_open',
            field=models.PositiveIntegerField(default=0, help_text='Total number of open tickets'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='total_resolved',
            field=models.PositiveIntegerField(default=0, help_text='Total number of resolved tickets'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='total_tickets',
            field=models.PositiveIntegerField(default=0, help_text='Total number of tickets'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Date and time when customer was last updated'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['nida_number'], name='tickets_cus_nida_nu_634db4_idx'),
        ),
        migrations.AddConstraint(
            model_name='customer',
            constraint=models.CheckConstraint(check=models.Q(('gender__in', ['M', 'F', 'O', 'N']), ('gender__isnull', True), _connector='OR'), name='valid_gender_constraint'),
        ),
    ]
