# Generated by Django 4.2.16 on 2026-06-05 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0011_add_customer_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='customer_email',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='customer_name',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='customer_phone',
        ),
        migrations.AlterField(
            model_name='ticket',
            name='customer',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='tickets.customer'),
            preserve_default=False,
        ),
    ]
