# Generated by Django 4.2.16 on 2026-06-09 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KPIReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_tickets', models.PositiveIntegerField(default=0)),
                ('resolved_tickets', models.PositiveIntegerField(default=0)),
                ('open_tickets', models.PositiveIntegerField(default=0)),
                ('avg_resolution_time', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('escalated_tickets', models.PositiveIntegerField(default=0)),
                ('reopened_tickets', models.PositiveIntegerField(default=0)),
                ('csat_score', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('sla_compliance_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'KPI Report',
                'verbose_name_plural': 'KPI Reports',
                'ordering': ['-created_at'],
            },
        ),
    ]
