# Generated by Django 4.2.29 on 2026-06-01 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kpireport',
            options={'ordering': ['-created_at'], 'verbose_name': 'KPI Report', 'verbose_name_plural': 'KPI Reports'},
        ),
        migrations.AddField(
            model_name='kpireport',
            name='csat_score',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3),
        ),
        migrations.AddField(
            model_name='kpireport',
            name='escalated_tickets',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='kpireport',
            name='reopened_tickets',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='kpireport',
            name='sla_compliance_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='kpireport',
            name='avg_resolution_time',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='kpireport',
            name='open_tickets',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='kpireport',
            name='resolved_tickets',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='kpireport',
            name='total_tickets',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
