# Generated by Django 4.2.16 on 2026-06-28 00:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_rank'),
        ('channels', '0002_channel_created_at_channel_status_channel_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='team',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='channels', to='users.team'),
            preserve_default=False,
        ),
    ]
